spring:
  application:
    name: config-server
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/York-Luo/SpringcloudConfig/
          search-paths: respo
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

